### ISSUE TITLE
Support parsing multiple exception types in catch clauses

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/tolerant-php-parser#103]
PHP 7.1 introduced support for catching multiple exception types:
https://wiki.php.net/rfc/multiple-catch

![image](https://cloud.githubusercontent.com/assets/762848/22870621/e999f0c2-f176-11e6-871a-07d976f89215.png)

We should handle this condition on the parser by parsing as a delimited list of qualified names, where the delimiter is the `TokenKind::BarToken`, and we should be able to reuse the logic from `parseQualifiedNameList`

**Comment by nesl247** [comment]
Any update on this?

**Comment by BPScott** [comment]
I've filed an issue with php-langspec as this is not currently documented and tested upstream: https://github.com/php/php-langspec/issues/216

**Comment by TysonAndre** [comment]
My thoughts on solving this:

Add a new property to the tolerant-php-parser object representing the `catch{}` Node (i.e. CatchClause, parsed by parseCatchClause).

CatchClause->remainingQualifiedNameList would either be null or begin with `|` and end with `T1 [ | T2...]`. It would be parsed if the next token was `|`. It would be immediately after qualifiedName.

- In a future backwards incompatible release (1.0 if following semver?), rename CatchClause->qualifiedName to qualifiedNameList and remove remainingQualifiedNameList

**Comment by jens1o** [comment]
@Zerquix18 Feel free to file a pr :)

**Comment by felixfbecker** [comment]
@Zerquix18 Seriously, whining won't make it be fixed any faster. A PR will. This project is driven by community contributions.
