### ISSUE TITLE
Allow abstract functions (new in PHP 7.2)

### ISSUE THREAD

**Issue by jens1o** [Microsoft/tolerant-php-parser#134]
Currently, I get this:
```php
<?php
abstract class A           { abstract function bar(stdClass $x);  }
abstract class B extends A { abstract function bar($x): stdClass; }
class C extends B          { function bar($x): stdClass{} }
```
![image](https://user-images.githubusercontent.com/11234139/26929232-2fc86fd2-4c59-11e7-9751-55f6f81e3013.png)

Although this is [valid as of php 7.2](https://wiki.php.net/rfc/allow-abstract-function-override), whereas the first alpha has been released today: http://news.php.net/php.internals/99452

May I provide a PR which removes the diagnostic?

**Comment by roblourens** [comment]
I don't get this error?

![image](https://user-images.githubusercontent.com/323878/26992246-9a861702-4d12-11e7-920e-cb917f33881e.png)

**Comment by jens1o** [comment]
Dump question: Is this error thrown by the php parser or by the lexer?

**Comment by roblourens** [comment]
This is actually coming from vscode's built-in barebones validation which comes from PHP itself. It can be disabled with `"php.validate.enable": false`. It's using PHP on your path, or `php.executablePath`.

**Comment by jens1o** [comment]
Okay, then it's supposed to use php 7.1 and not php 7.2. That explains it. Thanks!
