### ISSUE TITLE
ForeachSatement->foreachValue switches

### ISSUE THREAD

**Issue by jens1o** [Microsoft/tolerant-php-parser#142]
Having following:
```php
<?php
foreach ([0, 1, 2, 3, 4] as $array) {
    echo $array;
}
```
with `$ast->statementList[1]->foreachValue->getText()` results in `"$array"`.

Having this:
```php
<?php
foreach ([0, 1, 2, 3, 4] as $array => $index) {
    echo $array;
}
```
results `$ast->statementList[1]->foreachValue->getText()` = `"$index"`.

**Comment by felixfbecker** [comment]
Which is as expected?

**Comment by jens1o** [comment]
foreachValue is always `$array`, regardless there is an index.

**Comment by felixfbecker** [comment]
This contradicts your original post, you said

> results `$ast->statementList[1]->foreachValue->getText() = "$index"`.

Maybe you made a mistake in naming the variables? This would make more sense:
```php
foreach ([1, 2, 3] as $number)
foreach ([1, 2, 3] as $index => $number)
```

**Comment by jens1o** [comment]
oh, yes.

**Comment by roblourens** [comment]
I don't understand. In Felix's example, `foreachValue` should always be `$number`, right? That appears to be the case now?

**Comment by jens1o** [comment]
Okay, I was unsure, because I thought it should be consistence, no matter when I change the code.

**Comment by felixfbecker** [comment]
But it is consistent. `foreachValue` is always the value of the iteration elements. `foreachKey` is always the key of the iteration elements. The latter is simply optional.

**Comment by jens1o** [comment]
Okay, thanks. That explains it. Can this be in the docblock of the `ForeachStatement` class, so others understand it better than me?
