### ISSUE TITLE
Possible opcache bug

### ISSUE THREAD

**Issue by vakata** [Microsoft/tolerant-php-parser#155]
Using PHP v.7.1.0 on windows I stumbled upon a very strange problem.

This is my code:
```php
use Microsoft\PhpParser\{DiagnosticsProvider, Node, Parser, PositionUtilities};

// Instantiate new parser instance
$parser = new Parser();

$src = <<<'EOT'
<?php
class A {
  public function a() {
    return $this;
  }
}
class B extends A {
  public function b() {}
}

$b = new B;
$b->a()->
EOT;

// Return and print an AST from string contents
$astNode = $parser->parseSourceFile($src);
```

When running with opcache enabled after the first successful run all subsequent runs fail with:
**Uncaught Error: Cannot use object of type Microsoft\PhpParser\Token as array in D:\work\source\_archive\tolerant-php-parser\src\Parser.php:1508**
This is the offending line:
```php
list($prevNewPrecedence, $prevAssociativity) = self::UNKNOWN_PRECEDENCE_AND_ASSOCIATIVITY;
```

The problem can be fixed in one of three ways:
1) using ```static``` instead of ```self``` when accessing the constant
2) not using ```list``` but assigning the variables directly to [0] and [1]
3) by disabling opcache ```ini_set('opcache.enable', 0);```

I am not sure what to make of this, I would have filed a PHP bug but I am afraid I can't create an isolated example. There are a few reports about problems with opcache and PHP 7.1, but I am not sure they are related:
https://bugs.php.net/search.php?cmd=display&order_by=id&direction=DESC&limit=30&phpver=7.1&package_name[]=opcache

**Comment by vakata** [comment]
It really was an issue with PHP opcache, and it is resolved: https://bugs.php.net/bug.php?id=74019

**Comment by roblourens** [comment]
Thanks for the report, and following up with PHP. I think this is the same thing we were looking at in this issue: https://github.com/felixfbecker/php-language-server/issues/418
