### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, array given

### ISSUE THREAD

**Issue by Petah** [Microsoft/tolerant-php-parser#159]
Get an error trying to run the example:

    PHP Fatal error:  Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, array given

on this line:

    var_dump(iterator_to_array($errors));

**Comment by roblourens** [comment]
Fixed in #160
