### ISSUE TITLE
Implement a `FunctionLike` interface

### ISSUE THREAD

**Issue by roblourens** [Microsoft/tolerant-php-parser#162]
See https://github.com/felixfbecker/php-language-server/pull/438#issuecomment-316351727 and `isFunctionLike` in php-language-server's `ParserHelpers.php`

**Comment by jens1o** [comment]
Am I wrong or is this a quite easy task?

I just add a new interface and map them to the points how the parserhelpers recognizes them?

**Comment by roblourens** [comment]
Yes it would be quite easy.

**Comment by jens1o** [comment]
I'm going to do this in the next minutes.

**Comment by roblourens** [comment]
Ok, I started a stopwatch 😁

**Comment by jens1o** [comment]
Quality before speed 😛
