### ISSUE TITLE
Come up with better consistent names for getStart/getEndPosition

### ISSUE THREAD

**Issue by roblourens** [microsoft/tolerant-php-parser#166]
https://github.com/Microsoft/tolerant-php-parser/pull/156#discussion_r122614440

**Comment by TysonAndre** [comment]
In the meantime, could you add an alias to either of the classes (e.g. add getStartPosition() to Node, keeping the existing getStart() method and maybe marking it as deprecated).

Adding a new alias should be backwards compatible, and lets users get an offset without doing an instanceof check

**Comment by TysonAndre** [comment]
The Node and Token methods were changed in #349
