### ISSUE TITLE
ClassLike Interface

### ISSUE THREAD

**Issue by dantleech** [Microsoft/tolerant-php-parser#171]
Similar to https://github.com/Microsoft/tolerant-php-parser/issues/162. Would it make sense to implement a ClassLike interface for `ClassDeclaration`, `InterfaceDeclaration` and `TraitDeclaration` ?

**Comment by roblourens** [comment]
Yes, I think so. That kind of check does show up in several places like here https://github.com/felixfbecker/php-language-server/blob/master/src/DefinitionResolver.php#L1104.
