### ISSUE TITLE
Support multi catch type exception handling

### ISSUE THREAD

**Issue by roblourens** [Microsoft/tolerant-php-parser#173]
From https://github.com/felixfbecker/php-language-server/issues/475

> Testing with:
> ```
>try {
> //...
> } catch (FirstException | SecondException $e) {
> //...
> }
> ```
>got "Variable name expected" error. Looks like it uses old version of PHP.

http://php.net/manual/en/migration71.new-features.php#migration71.new-features.mulit-catch-exception-handling

**Comment by nesl247** [comment]
This is a duplicate of #103

**Comment by roblourens** [comment]
Why did I not see that? I knew there was an issue. Thanks.
