### ISSUE TITLE
Incorrect error reported when calling a function returned from another function

### ISSUE THREAD

**Issue by AustP** [Microsoft/tolerant-php-parser#175]
Given the following code:

```
<?php

function getEchoFunction()
{
    return function ($message) {
        echo($message);
    };
}

getEchoFunction()('hey');
```

An error is reported. It looks like it doesn't like calling functions inline like that.

> Error: ';' expected. Line 10:18

Changing the code to:

```
$echo = getEchoFunction();
$echo('hey');
```
 
works as expected.

(Copied from https://github.com/atom/ide-php/issues/26)

**Comment by jens1o** [comment]
@roblourens This can be closed, can't it?

**Comment by jens1o** [comment]
@roblourens When do you schedule the next release? I'd love to see the improved parser version in daily usage. :)

**Comment by roblourens** [comment]
Just pushed 0.0.9 👍
