### ISSUE TITLE
Add way to check library version (e.g. const Parser::VERSION)

### ISSUE THREAD

**Issue by TysonAndre** [Microsoft/tolerant-php-parser#192]
If a library using Tolerant-PHP-Parser has a version range (e.g. ~1.0.0), it may need some workarounds for older/newer versions (e.g. bug was fixed in 1.0.3 changing resulting AST for invalid PHP input)

It may be useful to be able to query the version to have conditional logic. (Same as composer version)

**Comment by roblourens** [comment]
Ideally a library should know which version of the parser it's designed to work against. And if the parser produces an AST which isn't compatible with older versions, it would respect semver. So you shouldn't need to check the parser version in code, right?

**Comment by TysonAndre** [comment]
Semver uses patch version for bug fixes. Does generating a slightly different AST for invalid php code fall under a bug fix?

1. A bug such as https://github.com/Microsoft/tolerant-php-parser/issues/188 exists in 0.0.5
2. It gets worked around and a fix is released in 0.0.6
3. Old code which expected the buggy AST (e.g. autocompleting variable names) stops working.

---

I guess there are workarounds, such as expecting exact versions of tolerant-php-parser (makes it harder for libraries to coexist in vendor/) or bumping minimum versions and releasing fixes whenever a patch version has an incompatibility.

- Having Parser::VERSION would help if the incompatibility (with 0.0.5) was noticed in 0.0.6-dev before 0.0.6 was released
- Otherwise, not that useful.

**Comment by roblourens** [comment]
Semver.org:
> PATCH version when you make *backwards-compatible* bug fixes.

I think that if a bug fix introduces a breaking change, then it would be a semver-major change. It doesn't matter why back-compat is broken - bug fix, design change, new feature.
