### ISSUE TITLE
continue(1) and break(1) should not be syntax errors

### ISSUE THREAD

**Issue by MadHed** [Microsoft/tolerant-php-parser#195]
![continue](https://user-images.githubusercontent.com/2094371/30820871-93db0a00-a223-11e7-888c-25bc48c2c691.png)

The optional numeric constant for `break` and `continue` statements can be enclosed in parentheses which is erroneously reported as a syntax error:

`';' expected.`

See here: [http://sandbox.onlinephpfunctions.com/code/19bee6f4f7dc93a6a146950fd9877a438c131897](http://sandbox.onlinephpfunctions.com/code/19bee6f4f7dc93a6a146950fd9877a438c131897)

**Comment by roblourens** [comment]
http://php.net/manual/en/control-structures.continue.php

**Comment by mousetraps** [comment]
Would also be good to update the language spec

![image](https://user-images.githubusercontent.com/762848/30825365-8fd8dd74-a1e7-11e7-8330-f9431092d0ea.png)
https://github.com/php/php-langspec/blob/master/spec/19-grammar.md#grammar-continue-statement

**Comment by MadHed** [comment]
Just opened a pull request at php-langspec: https://github.com/php/php-langspec/pull/211
