### ISSUE TITLE
Create 0.0.6 release

### ISSUE THREAD

**Issue by TysonAndre** [Microsoft/tolerant-php-parser#201]
The previous release was 2 months ago, there were performance improvements and minor bug fixes and AST changes (e.g. breakout) since then.

Having this release is useful for composer projects that are developing against the latest tolerant-php-parser

**Comment by felixfbecker** [comment]
@roblourens could you cut a new release? I think I got quite a few bug reports in the PHP LS that are already fixed here in master

**Comment by roblourens** [comment]
Done!
