### ISSUE TITLE
Incorrect PHP error when `PHP Intellisense` extension is installed on VSCode

### ISSUE THREAD

**Issue by vboctor** [Microsoft/tolerant-php-parser#214]
The author of the plugin indicated that [I should report the issue here](https://github.com/felixfbecker/php-language-server/issues/544).

In the following function, VS Code shows an `[php] '}' expected.` error and adds a red marker under `p_match`.

```
function test() {
    ...
    return "<a ${t_url_href}${t_url_target}>${p_match[1]}</a>";
}
```

Versions:
- VSCode Version: 1.18.1
- OS Version: MacOS 10.13.1

Doesn't reproduce when running `code --disable-extensions`.

**Comment by mattacosta** [comment]
@roblourens Just a heads up, this was also fixed by #226 and can be closed as well.
