### ISSUE TITLE
'Expression' expected.

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/tolerant-php-parser#237]
_From @marcing on February 28, 2018 11:54_

``
public function test()
{
    end:
}
``
Label at the end of function generates an error "'Expression' expected".
It is a valid php syntax.

Cheers

_Copied from original issue: felixfbecker/php-language-server#613_

**Comment by TysonAndre** [comment]
Possible duplicate of https://github.com/Microsoft/tolerant-php-parser/issues/154
