### ISSUE TITLE
Publish a 0.0.14 release

### ISSUE THREAD

**Issue by TysonAndre** [Microsoft/tolerant-php-parser#262]
Changes have been added to avoid emitting notices that can crash language servers (in parseTernaryExpression)

- If possible, include #260 and #261 (these bugs were less common, and were identified by fuzzing)

The previous 0.0.13 release was on August 7th.

**Comment by roblourens** [comment]
Done

**Comment by roblourens** [comment]
Will publish again after merging the PRs

**Comment by TysonAndre** [comment]
Thanks!
