### ISSUE TITLE
0.0.16 release missing from packagist - Please manually trigger a packagist build

### ISSUE THREAD

**Issue by TysonAndre** [Microsoft/tolerant-php-parser#275]
https://packagist.org/packages/microsoft/tolerant-php-parser is currently v0.0.15.

> there is an known issue with github hooks: pushing a tag pointing to a commit which is already available on Github (and so not pushing any new commit) does not trigger the push webhook, and so Packagist is not notified.
**The workaround is to trigger a manual update in the packagist UI. Otherwise the tag will be picked only the next time you push a commit to github.**

**Comment by roblourens** [comment]
Done!

**Comment by TysonAndre** [comment]
Not sure how you fixed this, so mentioning this: Packages needs additional permissions for builds to be automatically triggered as of early 2019.

https://packagist.org/about#how-to-update-packages

> Make sure the [Packagist application](https://github.com/settings/connections/applications/a059f127e1c09c04aa5a) has access to all the GitHub organizations you need to publish packages from.

They also provide instructions for configuring GitHub webhooks manually

**Comment by roblourens** [comment]
Thanks for pointing that out. I think I've set it up correctly now.
