### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by gnoe** [microsoft/tolerant-php-parser#300]
Parsing file: [Configuration.php from doctrine/doctrine-bundle](https://github.com/doctrine/DoctrineBundle/blob/1.12.x/DependencyInjection/Configuration.php)

**Comment by TysonAndre** [comment]
This is an issue with your usage of xdebug. Either

1. Disable xdebug before running the application using this library, e.g. with composer/xdebug-handler, or
2. Set xdebug.max_nesting_level to a much higher value before starting php (in php.ini or with `php -d xdebug.max_nesting_level=9999 ...` - https://xdebug.org/docs/basic#max_nesting_level

**Comment by gnoe** [comment]
I will increase the xdebug.max_nesting level
Thank you so much!

**Comment by roblourens** [comment]
Thanks @TysonAndre
