### ISSUE TITLE
')','(','{' expected - Incorrect intellisense

### ISSUE THREAD

**Issue by OnlyPikachudev** [microsoft/tolerant-php-parser#312]
### Randomly added these errors out of the blue.

![Sample1](https://i.imgur.com/GDWPAZ3.png "Original code")
![sample2](https://i.imgur.com/NqMbKP8.png "Error")

**Comment by roblourens** [comment]
If you reload the window, does it go away? If not, can you post the text of the file here?

**Comment by OnlyPikachudev** [comment]
> If you reload the window, does it go away? If not, can you post the text of the file here?

It works if you close entire VS Code. But reload does not work.

`<?php
require('../../config/config.php');

function Login($username, $password) {
    $conn = new mysqli(DB_HOSTNAME, DB_USERNAME, DB_PASSWORD, DB_AUTH);

    if ($conn->connect_error) {
        die("Connection failed");
    }

    $sql = "asd";
}

?>`

For code.

**Comment by roblourens** [comment]
Ok, that case please file the issue on the PHP extension that you are using.
