### ISSUE TITLE
Use a dedicated library for tree handling

### ISSUE THREAD

**Issue by drupol** [microsoft/tolerant-php-parser#316]
Hi,

I noticed that the class src/Node.php is basically re implementing a tree structure on itself.

Would you be interested to use a contrib library for handling the tree ? Would it be an option ?

**Comment by roblourens** [comment]
Probably not, but I don't quite understand what you mean. Can you explain more and what the advantages would be?

**Comment by drupol** [comment]
Hi Rob,

Recently I had to find an easy solution to make images from an Abstract Syntax Tree of a PHP file.

I started investigating into [nikic/php-parser](https://github.com/nikic/php-parser) and I used it at first to build my package.

Then I discovered this package. I really like the tree structure, it was much easier to parse.

You can find the package here: https://github.com/loophp/phptree-ast-generator
It's based on [loophp/phptree](https://github.com/loophp/phptree) and I recently added [a custom importer for microsoft/tolerant-php-parser](https://github.com/loophp/phptree/commit/50b7f4f571371cb3d7abcd1df1d4aa05387bb81c).

It's a command line tool, here are some examples:

To generate an image:
`./bin/ast generate -p microsoft -t image -d graph.svg src/Command/Generator.php`

To generate a dot script:
`./bin/ast generate -p microsoft -d graph.dot src/Command/Generator.php`

So, now to answer your question.

I was wondering why you were not using a dedicated library for handling trees, so you can dedicate all that logic and tests to the contrib library.
I built [loophp/phptree](https://github.com/loophp/phptree), it might maybe a good candidate for this.

Let me know what you think.

**Comment by roblourens** [comment]
Cool, thanks for sharing. And thanks for the suggestion, but I don't think we have enough complex tree logic here to justify it. Also, I am maintaining this project but not actively enough that I have the time to work on or validate a change like that.
