### ISSUE TITLE
Publish a 0.0.21 release with support for lexing changes in php 8.0 (T_NAME_*)?

### ISSUE THREAD

**Issue by TysonAndre** [microsoft/tolerant-php-parser#332]
See #331 - People using php 8.0 dev won't be able to use this library until https://wiki.php.net/rfc/namespaced_names_as_token is supported.

The feature freeze is on August 4th, the only thing that has the potential to change after that is the attributes syntax, which I haven't  worked on supporting yet (for that reason).

**Comment by TysonAndre** [comment]
@roblourens - thoughts? the rest of the 8.0 support (named arguments, nullsafe operator, etc) might take a while, so I'd prefer if the bug fixes for lexing were released earlier

**Comment by roblourens** [comment]
Done, sorry for the delay

**Comment by TysonAndre** [comment]
Thanks!

**Comment by roblourens** [comment]
Also did .22 with the PR from today.
