### ISSUE TITLE
Enhance contributing guide about test cases

### ISSUE THREAD

**Issue by PythooonUser** [microsoft/tolerant-php-parser#338]
## Summary
The contributing guide talks about creating test cases for the parser. However, some parts of this section can be made clearer.
- It leaves out that also `.diag` files need to be generated
- It leaves out that new test cases can only be tested when they have previously been committed to version control, as a `git checkout` happens internally

**Comment by TysonAndre** [comment]
I'd agree, it'd help new contributors

> It leaves out that also `.diag` files need to be generated

Those get generated by running ParserGrammarTest 

> It leaves out that new test cases can only be tested when they have previously been committed to version control, as a git checkout happens internally

I thought the git checkout was for .diag and .tree before re-running the tests, not for the .php, but I forget

There's also "you should set `short_open_tags=0` if using a php build supporting those (e.g. locally built)"
