### ISSUE TITLE
Common Formatting Of Code Base

### ISSUE THREAD

**Issue by PythooonUser** [microsoft/tolerant-php-parser#340]
## Summary
When creating PRs I noticed my VS Code formatting settings for PHP are different, and also among the code base small code style differences are present.

Is a common formatting of PHP files adopted for this project, but not mentioned in the contributing guide? If so, it should be made clear how to configure and use it.

Otherwise, there is a [prettier plugin for PHP](https://github.com/prettier/plugin-php) that could be used to enforce a common code style among the code base and developers.

**Comment by TysonAndre** [comment]
There's also phpcbf - https://github.com/phan/phan/blob/master/phpcs.xml and https://github.com/phan/phan/blob/master/internal/phpcbf is a phpcs config I use for another project to follow PSR-2 and PSR-12.

- psr config for tolerant-php-parser should use camelCase instead
- I don't really deeply care where braces go, but PSR-12 recommended they go on a new line
- PSR-12 suggests `): ReturnType`, with no space before `:`

I don't consider formatting a high priority, though - I'll defer to the maintainers on this
