### ISSUE TITLE
Publish a new release supporting php 8.2 syntax?

### ISSUE THREAD

**Issue by TysonAndre** [microsoft/tolerant-php-parser#376]
See ~~#370 #374 #375~~ and #382 , in addition to changes that were already merged to support php 8.2 syntax or other improvements

**Comment by TysonAndre** [comment]
@roblourens fyi - I think the latest `main` commit should be fine to release, though https://github.com/microsoft/tolerant-php-parser/pull/382 would be nice to have

**Comment by TysonAndre** [comment]
@roblourens - pinging again about publishing a release since it's easy to lose track of notifications on the weekend.

PHP 8.2.0RC2 is out https://www.php.net/ - https://wiki.php.net/todo/php82 will be out in November

**Comment by roblourens** [comment]
I got to this last - everything I merged should be fine to go out in a 0.1.2 right?

**Comment by TysonAndre** [comment]
Yes - everything merged is fine to go out in a 0.1.2 release

- Tests of tolerant-php-parser pass in ci in 8.2.0beta2 and locally in a recent 8.2-dev build
- Tests of Phan pass in 8.2/7.4 (e.g. the component that converts `Microsoft\PhpParser` to php-ast `ast\Node` with/without error tolerance) after replacing vendor/microsoft/tolerant-php-parser/src with a35ec03ed3d76940e45955acc98fc8c43f6da081
- I looked over recent changes and they all looked good

**Comment by TysonAndre** [comment]
I realized one thing - the way HaltCompilerStatement is parsed could use some work for easily inferring `__HALT_COMPILER_OFFSET__` and testing edge cases - https://github.com/microsoft/tolerant-php-parser/pull/389

If a release is created before that I can just keep the property name of `semicolon` for `;` or `?>` or `?>\n`

**Comment by TysonAndre** [comment]
>I realized one thing - the way HaltCompilerStatement is parsed could use some work for easily inferring __HALT_COMPILER_OFFSET__ and testing edge cases - https://github.com/microsoft/tolerant-php-parser/pull/389

But other than #389, there were no issues with extracting the needed information from new parsed nodes (e.g. exact same computed offset for AST_HALT_COMPILER) when I started using tolerant-php-parser `main` to test. https://github.com/phan/phan/pull/4730 has tests passing for converting them to `ast\Node` with the same fields

**Comment by TysonAndre** [comment]
@roblourens #389 continues to be the only PR with fixes I'd want before creating a release with the other changes - could you review that?

- If you want to keep the existing `semicolon` name instead then feel free to make that change

**Comment by TysonAndre** [comment]
https://github.com/microsoft/tolerant-php-parser/pull/391 should also be included to fix a regression

**Comment by roblourens** [comment]
Done
