### ISSUE TITLE
Use `strrpos` instead of `strpos` in `GetLineCharacterPositionFromPosition`

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/tolerant-php-parser#71]
`strrpos` should be far more efficient than the current `strpos` + while loop. 
https://github.com/Microsoft/tolerant-php-parser/blob/master/src/Utilities.php#L77-L94

**Comment by villfa** [comment]
@mousetraps I'm not sure about the expected behaviour in some cases.
What should be the result when :
.  $pos is greater than the text length
.  $pos is negative

Thanks

**Comment by mousetraps** [comment]
@villfa - I've answered your question in the form of a PR that adds some tests - #74 :smiley:

**Comment by mousetraps** [comment]
Also, FYI I've removed the up-for-grabs label, and marked the issue as in-progress since it sounds like you've already started on it. Lmk if that's not the case and I'll undo.
