### ISSUE TITLE
Consider parsing NamespaceDefinition as parent of future statements

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/tolerant-php-parser#81]
Currently the namespace definition only includes a compound statement or semicolon token as one if it's children. Parsing future statements as a child rather than a separate statement would help us optimize for operations where we want to find the fully qualified name by simply searching for the first ancestor. 

We would terminate parsing the namespace when another namespace definition occurs. There may be some edge cases here, though, so it's worth discussing.

**Comment by nikic** [comment]
Name resolution needs not just the namespace, but also the import table. Uses can occur anywhere at the top-level of a namespace (not necessarily at the start of the namespace), so nesting statements into the namespace node will probably not buy you anything from a performance point of view.

PHP-Parser does move statements into the namespace node, but overall I'm not sure whether doing this was the right choice.

**Comment by mousetraps** [comment]
Ahh, yes, so it wouldn't really cover every scenario (it would would still help for class/function definitions, but I'm not sure that's important enough to special-case.). In that case, unless there's some compelling API reason to parse differently that doesn't make sense for a helper method, I would prefer to stick as closely as possible to the grammar.

```
namespace-definition:
   namespace   name   ;
   namespace   nameopt   compound-statement
```
