### ISSUE TITLE
Add PHPCS for code style validation

### ISSUE THREAD

**Issue by decanus** [Microsoft/tolerant-php-parser#83]
Just an idea to slowly start improving the code style

**Comment by mousetraps** [comment]
A git pre-commit hook would be slick too. ✨

**Comment by decanus** [comment]
We could think about adding travis

**Comment by felixfbecker** [comment]
Yes please. It's pretty easy:

https://github.com/felixfbecker/php-language-server/blob/master/phpcs.xml.dist
https://github.com/felixfbecker/php-language-server/blob/master/.travis.yml#L18
