### ISSUE TITLE
Parser doesn't properly parse namespace-use-clause list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/tolerant-php-parser#87]
The below code gets parsed fine
```php
<?php
namespace A;
use A;
```

However, if you include another namespace-use-clause, it does not get parsed properly.
```php
<?php
namespace A;
use A, B;
```
![image](https://cloud.githubusercontent.com/assets/762848/22672659/1f91618e-ec8a-11e6-8ca9-632088032a95.png)

**Comment by mousetraps** [comment]
Also, if anyone is interested in working on this:

**Where to start:**
* https://github.com/Microsoft/tolerant-php-parser/blob/master/src/Node/Statement/NamespaceUseDeclaration.php
* https://github.com/Microsoft/tolerant-php-parser/blob/master/src/Parser.php#L2556-L2593

**Grammar (for reference):**
```
namespace-use-declaration:
   use   namespace-function-or-constopt   namespace-use-clauses   ;
   use   namespace-function-or-const   \opt   namespace-name   \   {   namespace-use-group-clauses-1   }   ;
   use   \opt   namespace-name   \   {   namespace-use-group-clauses-2   }   ;

namespace-use-clauses:
   namespace-use-clause
   namespace-use-clauses   ,   namespace-use-clause

namespace-use-clause:
   qualified-name   namespace-aliasing-clauseopt
```
https://github.com/php/php-langspec/blob/master/spec/19-grammar.md#user-content-grammar-namespace-use-declaration

**Comment by runz0rd** [comment]
Mind if I grab this one?

**Comment by mousetraps** [comment]
@runz0rd go ahead! Removed the up-for-grabs label, and marked it as in-progress.

Also FYI, I'm currently working on #95 which shouldn't conflict, but would eventually take a dependency on this work so lmk if you decide to do anything drastic or notice some other issues in this area.
