### ISSUE TITLE
Question: Will this be used with standard Visual Studio?

### ISSUE THREAD

**Issue by gulshan** [Microsoft/tolerant-php-parser#92]
Will this be used with standard Visual Studio not vscode?

**Comment by mousetraps** [comment]
There's no reason it can't be consumed by a Visual Studio extension, but right now our primary focus is Visual Studio Code. See also #36 and #47.

For Visual Studio, I suggest taking a look at [PHP Tools for Visual Studio](https://www.devsense.com/) by DEVSENSE if you haven't already. I haven't personally tried it, but it looks pretty great.
