### ISSUE TITLE
Support parsing nullable types

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/tolerant-php-parser#97]
PHP 7.1 supports nullable types by prefixing the type with a question mark. 
https://wiki.php.net/rfc/nullable_types

This is also currently missing from the `type-declaration` definition in the language spec, so we should update it there too. https://github.com/php/php-langspec/blob/master/spec/19-grammar.md#user-content-grammar-type-declaration

**Comment by roblourens** [comment]
FYI @felixfbecker, I'm adding this label to things that issues that represent regressions in the lang server vs the old parser.

**Comment by jens1o** [comment]
Nice idea!
